### ISSUE TITLE
Problem in some barotropic applications

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#21]
With Matt's code included in user/ksh/open_bc, I now get:
```
At line 351 of file //center/d/kate/ESMG/ESMG-configs/src/MOM6/src/ALE/MOM_regridding.F90
Fortran runtime error: Index '0' of dimension 1 of array 'gv%rlay' below lower bound of 1
-------------------------------------------------------
```
This is both Tidal_bay and Supercritical.

**Comment by MJHarrison-GFDL** [comment]
This is a separate issue unrelated to OBCs. Introduced with newer auto diagnostic vertical remapping.

supercritical/tidal_bay/rossby_soliton all have NK=1, which breaks the model unless:

NUM_DIAG_COORDS = 0

**Comment by kshedstrom** [comment]
Maybe so, but I wasn't having this problem in dev/master. Did you change something about the vertical coordinate assumptions? Anyway, adding that to MOM_input gives me:

> At line 2954 of file //center/d/kate/ESMG/ESMG-configs/src/MOM6/src/core/MOM_barotropic.F90
> Fortran runtime error: Index '1' of dimension 1 of array 'segment%cg' below lower bound of 51

**Comment by MJHarrison-GFDL** [comment]
No. I didn't change anything related to the vertical coordinate assumptions.

**Comment by kshedstrom** [comment]
I added stuff allocating segment fields like Cg to the tidal bay file in the user directory and now it runs. Computing Cg is using a different eta than in the old code - is that why answers change? In fact, Cg is now computed on the baroclinic timescale.

**Comment by MJHarrison-GFDL** [comment]
update_obc_segment_data is not currently being called. It should be called from continuity (via update_obc_data). 

What is the correct condition for active segment data? 

(If segvals are used, then it's inactive,otherwise we could assume that the segment values are being updated, and velocities, transports, thickness are being updated on the baroclinic timestep)

**Comment by kshedstrom** [comment]
We probably need more control from MOM_input. Some problems will have to provide one value that's good for all time (supercritical) while others will need a way to update the inputs (CCS1, tidal bay). ROMS has logic to see how many records are available in the required fields and what times go with them - will you fall off the end? If so, die now. Is there only one record? If so, just use it forever. There's other logic too, when time in the file has a cycle_length attribute, say repeat the 12 monthly climatology values for every year. I put in OBC%update_OBC to be used to call the updating, but it is now true for everything needing external values. How do you see this working in MOM6?

**Comment by MJHarrison-GFDL** [comment]
lol kate!! FMS:init_external_field  returns the time axis length.   We handle modulo time with different calendar types. We need this call to activate external segment data.

https://github.com/ESMG/MOM6/blob/user/ksh/open_bc/src/core/MOM_open_boundary.F90#L293

We can set OBC%update_OBC (per segment?) here.

**Comment by MJHarrison-GFDL** [comment]
Correction to my previous:

update_obc_segment_data should *NOT* be called from continuity. We are currently, calling from dynamics, which is called once per baroclinic timestep. Should this be moved up to step_MOM?
