### ISSUE TITLE
Describe new OBC segment options

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#3]
1. Protocol for reading from MOM_input
2. New type to describe segments
3. Write documentation in doxygen at bottom of MOM_open_boundary.F90

Proposal for parameter protocol:
- OBC_CONFIG = "none" turns off open boundaries
- If (OBC_CONFIG /= "none") then
- OBC_CONFIG = “SEGMENTS” turns on new protocol
  - OBC_NUMBER_OF_SEGMENTS = 2
  - OBC_SEGMENT_001 = "I=0,J=23:1,SIMPLE" (PRESCRIBED)
  - OBC_SEGMENT_002 = "I=45,J=5:15,FLATHER" (RADIATION, RADIATION+TIDES, …)
  - OBC_SEGMENT_001_DATA = “TEMP=file:xyz_%y.nc(theta),SALT=...”
  - OBC_SEGMENT_002_DATA = “SALT=IC”
  - or OBC_SEGMENT_002_DATA = “TEMP=DOME”
  - Note that we need to know which way each boundary is facing, i.e., which line of T-points is on the outside relative to the line of q-points. The index order for the I,J values will tell this, going around the domain counter-clockwise.
- The value of OBC_CONFIG determines method of setting inflow/boundary data (e.g. "DOME" as above, "SEGMENTS" to interpret more parameters
- If "SEGMENTS" then read OBC_SEGMENT_01_DATA = "..."
  - Obsolete APPLY_OBC_U/V and APPLY_OBC_U_FLATHER_\* as run-time parameters although they would exist internally.

Update: Changed to 3-digit numbering of segments

**Comment by adcroft** [comment]
Our idea of using I=0 to mean the western edge when J=JN:JS is a decreasing range, and I=0 to mean the eastern edge when J=JS:JN is an increasing range, works for single values (i.e. I=0) but not the ranges; J=0,0 has no obvious direction. Adopting python notation of "-1" for the last edge would be confusing to the python illiterates in a fortran code with NE indexing convention. How about using the character "N" to be the last element? e.g. "I=N,J=5,N-2" (part of eastern boundary), "I=0,J=N,0" (entire western boundary), "I=N-2,J=N-10:N-2" (eastern boundary condition 2 rows in), ...

**Comment by MJHarrison-GFDL** [comment]
I suppose this would be handy for  CIRCLE_OBCS  (I=N,J=1,N;J=N,I=N,1;...)
Maybe even (IJ=N)?

**Comment by raphaeldussin** [comment]
I have started working on the pre-processing package and put a preliminary version here : 

https://github.com/raphaeldussin/brushcutter

for now it only creates an empty shell for the netcdf file (no interpolation yet). The idea is that
we first describe the N segments then define variables telling what segment they belong to.
comments welcome about what attributes we want in the file,...

**Comment by kshedstrom** [comment]
How will we specify pure radiation, no outer values? Let that be the default unless set to a file or case?
Will there be a RADIATION_2D flag? In ROMS I think I always have it on, so that too could be a default. Do we need to support the simple case without it?

**Comment by adcroft** [comment]
I would suggest we make the option local to each boundary (for generality). What are the combinations of boundary conditions we are looking at? Prescribed, radiation-only, radiation+data, ... ?

**Comment by kshedstrom** [comment]
Yes, those are the main ones, and we do want to control them segment by segment. With tides, the data can be tidal plus sub-tidal. ROMS also provides "reduced physics" for barotropic momentum, when you have tidal elevations but not tidal currents. I usually use tidal model output and therefore have the currents and the elevations.

**Comment by kshedstrom** [comment]
There can be "no gradient" as well, which is like a wall for tracers, but not a wall for momentum.

Zygmunt doesn't like "reduced physics" any more than I do - you need the tidal velocities.

**Comment by kshedstrom** [comment]
Part of the radiation+nudging is specifying two timescales for the incoming and outgoing nudging. We usually set them in units of days, then convert to 1/s later.

What about having one option for T,S, another option for dye tracers? Will we ever want anything other than zero gradient for e, h?

**Comment by adcroft** [comment]
As I've started drafting the code for this I've realized it would be cleaner to simply obsolete OBC_CONFIG and control everything with OBC_NUMBER_OF_SEGMENTS. OBC_NUMBER_OF_SEGMENTS=0 turns OBCs off. Opinions?

Also, how about renaming OBC_SEGMENT_01_DATA to OBC_SEGMENT_01_FORCING ?

**Comment by kshedstrom** [comment]
In the ROMS culture, forcing is separate from boundary conditions,
primarily surface forcing fields. What about OBC_SEGMENT_01_VALUES?

**Comment by adcroft** [comment]
OBC_SEGMENT_001_VALUES will work...

Concerning OBC_CONFiG: in the draft I sent @kshedstrom yesterday, I've almost removed OBC_CONFIG from the "fixed" phase but we are relying on OBC_CONFIG to control how the "set data" is handled. I think we might need to keep a parameter like OBC_CONFIG for this purpose but we could rename it to something else to avoid confusion? OBC_VALUES_CONFIG?

In the OP, we said we would set OBC_CONFIG = “SEGMENTS” to turn on open boundaries. This is not coded yet. Currently OBC_NUMBER_OF_SEGMENTS is turning open boundaries on/off. To handle processing of @raphaeldussin 's files we could use:
> OBC_CONFIG ="none"

for no boundaries.

For parameter controlled:
> OBC_CONFIG = "SEGMENTS"
> OBC_NUMBER_OF_SEGMENTS = 1
> OBC_SEGMENT_001 = "I=N,J=0:N,SIMPLE"
> OBC_SEGMENT_001_VALUES = "DOME"

For file controlled:
> OBC_CONFIG = "FILE:filename"

And then the question of whether to keep the name OBC_CONFIG or change it to avoid confusion?

**Comment by kshedstrom** [comment]
Changing to OBC_VALUES_CONFIG sounds like a plan. So I should change the
corresponding string in the OBC structure too, I assume.

On Fri, Jul 29, 2016 at 12:28 PM, Alistair Adcroft <notifications@github.com

**Comment by kshedstrom** [comment]
If this is how we're doing SIMPLE OBCs, dare I tell you that I have about 6000 sources in the NW Gulf of Alaska domain? Each has daily transport with interannual variability and daily temperatures which cycle around for each year. The next GoA domain has coarser resolution but will include a number of BGC tracers for COBALT.

**Comment by kshedstrom** [comment]
One concern I have with getting rid of all array-based OBC info is that one can now set all edges to be open and count on the land masking to unset the appropriate land points. If we're not checking OBC_segment_u and OBC_segment_v, we'll have to check the land mask instead.
