### ISSUE TITLE
Zeroing accelerations

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#35]
I have a branch in which the accelerations are zeroed out. Some cases look much the same, but some do not:

* Tidal bay and shelfwave look much worse, as does the Kelvin wave (rotated Kelvin is especially bad). These have in common being driven by a Flather boundary condition on some "inflow" edge. Watching the shelfwave timestepping, for a point with **normal_vel_bt** of about 0.1, the **ubt** is about 0.05 after a batch of barotropic steps. Later, **u_av** ends up at 0.05, as does **ubt_cor**, while **up** = 1.6e-5. We need to get **up** on board with the stepping. None of these cases have a baroclinic OBC turned on.

What is the appropriate baroclinic OBC with Flather in barotropic domains?

**Comment by kshedstrom** [comment]
The answer is to only zero out the baroclinic accelerations. We need to replace the barotropic ones since they are used in the timestepping. Commit 01af8b7 fixes the above issues and cleans up the long-term behavior of the Channel problem (time is vertical axis):

![channel_old_e](https://cloud.githubusercontent.com/assets/444446/26227301/01794a60-3bde-11e7-8fcc-e34917810e30.png)
![channel_old](https://cloud.githubusercontent.com/assets/444446/26227302/017a347a-3bde-11e7-865d-7202051ed9c8.png)
![channel_new_e](https://cloud.githubusercontent.com/assets/444446/26227299/0177575a-3bde-11e7-8bd6-f246ba3d745c.png)
![channel_new](https://cloud.githubusercontent.com/assets/444446/26227300/0178511e-3bde-11e7-8ece-9040b6dae61e.png)

**Comment by adcroft** [comment]
Wow - looks a lot better!
