### ISSUE TITLE
Adding tracers to OBCs

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#39]
Right now, there is are segment%T and segment%S variables for the segments. This is missing out on any tracer registry for having umpteen tracers, while the "bad old way" has:
```
                if (associated(Tr(m)%OBC_in_u)) then
                  flux_x(I,m) = uhh(I)*Tr(m)%OBC_in_u(I,j,k)
                else ; flux_x(I,m) = uhh(I)*Tr(m)%OBC_inflow_conc ; endif
```
where each tracer can have an OBC value at u points and at v points, not to mention an OBC_inflow_conc. Time to build a tracer registry for each segment?

Meanwhile, I could get DOME working with segment%T since I assume there's only the one tracer there. Is that true? Plus get CCS using segment%T and segment%S once @MJHarrison-GFDL loads them with useful stuff. Or do we design the registry first? Any comments, @Hallberg-NOAA , @adcroft ?

**Comment by kshedstrom** [comment]
@MJHarrison-GFDL - I have connected the bad old 3d OBC tracer arrays to the OBC fluxes so that something actually happens when there are values in those arrays on the open boundaries. I figured that was the first step.

**Comment by kshedstrom** [comment]
The code quoted above now looks like:
```
                if (associated(OBC%segment(n)%Reg%Tr(m)%t)) then
                  flux_x(I,m) = uhh(I)*OBC%segment(n)%Reg%Tr(m)%t(I,j,k)
                else ; flux_x(I,m) = uhh(I)*OBC%segment(n)%Reg%Tr(m)%OBC_inflow_conc ; endif
```
and it is working. However, there is no sanity checking when registering the segment tracers that they match the regular tracers. The numbering from 1 to ntr(NTR) has to match between the two.

Similarly, if OBC T and S are loaded from files, they have to get loaded into the correct segment tracers to match the regular T and S tracers. Ditto COBALT, come the day.

**Comment by kshedstrom** [comment]
As I said in an email, not sure what's DOME's story. It has:

* 11 tracers all the same, none being T or S.
* all 11 tracers not evolving.
* no inflow value on any tracer.

**Comment by kshedstrom** [comment]
As for OBC segments that actually need memory, I'm not sure what to do. The tracer memory allocation looks like:
`allocate(CS%tr(isd:ied,jsd:jed,nz,NTR)) ; CS%tr(:,:,:,:) = 0.0`
How does one go about allocating an unknown number of segment tracer objects of differing shapes? A linked list?

**Comment by kshedstrom** [comment]
Arg, it was all working so well on one processor for simple problems (watching in the debugger). Now with CCS on four cores I have a problem...

**Comment by kshedstrom** [comment]
It wasn't about the number of cores, it was about the code in commit a02220e247, setting outside h values. I took this out recently and ran the usual symmetric tests, but didn't think to run CCS. Sure enough, the call to ALE regridding failed the way it did a year or so ago.

Now it runs for a while giving warnings from the ice, and finally dies:
```
WARNING from PE     0: Bad ice data End set_ice_surface_state ;  at  239.2  18.7 or i,j,k =    5   5   0; nbad =      1 on pe    0 ; T_sfc =   3.3770E+02, ps =   1.0000E+00, S_sfc =   3.7457E+01


FATAL from PE    12: lookup_es: saturation vapor pressure table overflow, nbad=      1    
```

**Comment by kshedstrom** [comment]
It will likely surprise no one that gfdl/dev/gfdl runs CCS1 for the full two months. The OBC_tracers code also runs if I comment out the boundary tracer stuff in MOM_tracer_advect (no answer changes). With the code as is, it runs for 26 days, then blows up, with a slowly growing instability on the western boundary.

I intend to finish the segment tracer registry stuff I started, but I'll need help with the stability problem at some point.

**Comment by MJHarrison-GFDL** [comment]
We have reproducibility failure across core counts in CCS1 (on dev/gfdl).  I am hunting down this issue which should help with the debugging.

**Comment by MJHarrison-GFDL** [comment]
Copied the segment tracers arrays into the segment_tracer_registry types and things look noisier and degraded - consistent with @kshedstrom 's experience.   The current code is initializing at the boundaries using the interior value at initialization - using updated segment values looks much worse. I am checking to make sure the segment data are not being corrupted.

**Comment by kshedstrom** [comment]
CCS1 tracers seem better after making the velocity nudging implicit. Closing this one now.
