### ISSUE TITLE
Map segments into masks and kinds

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#4]
1. Redefine kinds to be more useful
    - Need direction for all kinds, not just Flather: Split kind into direction and kind
2. Specify method for prescribing/assigning data to each segment

**Comment by kshedstrom** [comment]
Part 2 isn't done yet, is it?

**Comment by adcroft** [comment]
Correct. Part 2 is not done yet.

**Comment by kshedstrom** [comment]
Make a new issue for the data part.
