### ISSUE TITLE
Failure to build after latest merge

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#55]
I'm missing something...

> //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/ocean_data_assim/MOM_oda_driver.F90:41:6:
> 
>    use ocean_da_types_mod, only : grid_type, ocean_profile_type, ocean_control_struct
>       1
> Fatal Error: Can't open module file ‘ocean_da_types_mod.mod’ for reading at (1): No such file or directory
> compilation terminated.
> make[1]: *** [Makefile:197: MOM_oda_driver.o] Error 1

**Comment by adcroft** [comment]
It was broken briefly but fixed this morning.
Do another pull then
git submodule init
git submodule upgrade

**Comment by kshedstrom** [comment]
Thanks! My MOM6 was new enough, just needed this:

> git submodule init
> git submodule update
