### ISSUE TITLE
Barotropic OBC questions

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#58]
Hey gang, some of this code predates me, so I have questions:

* Why doesn't Cg_[uv] have the eta contribution? I think it should.
* In fact, in ROMS, both Cg_[uv] and H_[uv] are updated on the short steps. Do we want to keep it on the long steps?
* Is there a good reference for non-Boussinesq? I'm not testing that at all. Or is that for another day?
* Speaking of testing, I'm not testing barotropic "oblique" either. OK to delete that option? I stole it from ROMS, but we don't use it there either.

**Comment by adcroft** [comment]
- Does the eta contribution make much difference?
- Non-Boussinesq is meant to have happened (be the default) but we only have one test.
- I've no problems deleting unused code that won't be used in the future.

**Comment by kshedstrom** [comment]
* The eta contribution is going to be problem-dependent. One percent in my
Gulf of Alaska domain at most, but rather bigger in Hudson Strait in the
pan-Arctic domain. It's on tidal timescales, so I withdraw the suggestion
to update more frequently.
* I will make that unused code go away.
