### ISSUE TITLE
New test cases

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#6]
1. Exercise segments
2. Barotropic case
3. Exercise different kinds of OB

**Comment by kshedstrom** [comment]
Palau test - four open boundaries, no tides. Equatorial currents/counter-currents hit  the island and spin off vortices, reflections. Grids exist at two resolutions.

**Comment by adcroft** [comment]
Can the inputs (topo/grids) be described analytically or is this a real-world test? Is there a reference?

**Comment by kshedstrom** [comment]
It's a real world test and would come after the analytic cases. It would be
part of an ONR project with recent field work (the only part of my
involvement in MOM6 with actual funding).

**Comment by kshedstrom** [comment]
[Supercritical flow](http://marine.rutgers.edu/po/index.php?model=test-problems&title=supercritical)
The OBC on this little (barotropic!) gem ended my FVCOM career.

**Comment by kshedstrom** [comment]
I'll close this one - see #27 for some ideas for the next round of tests.
