### ISSUE TITLE
Bug in reentrant_y

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#60]
My new Chapman_channel/per_crossshore test has long-channel variations when it should not. In the first barotropic step, there is non-zero eta_PF outside the domain which leads to non-zero ubt at the outer edge. It gets zeroed out by the OBC code resetting ubt to prior values - but only on the segment. There remain nonzero values north and south of the segment. Must be a reentrant exchange missing?

FYI, this domain is periodic north-south with an open side to the east, wall at the west.

**Comment by adcroft** [comment]
circle_obcs is reentrant in both directions which was rotationally symmetric when we last checked. Is it perhaps the non-periodic boundaries causing the problem or different OBCs relative to circle?

**Comment by kshedstrom** [comment]
circle_obcs is well-behaved because gtot_x is zero outside so no pressure
accelerations can contribute to flow there. That isn't true in the new test.

Actually, circle_obcs has four open boundaries and is not at all reentrant.

**Comment by adcroft** [comment]
> Actually, circle_obcs has four open boundaries and is not at all reentrant.

Yes, exactly the opposite of what I said.

**Comment by kshedstrom** [comment]
Consensus is that we need to fix the segment specification if reentrant, not add more exchanges.

**Comment by kshedstrom** [comment]
Some possible cases:
    - segment not near reentrant edge
    - segment extends the full length of reentrant direction
       * if we grow the segment to fill reentrant halo, can we read data
         from file into it?
       * fix data reading later?
       * throw an error if we need data?
    - shorter segment is at one (or both) ends of the domain
       * make new segments for these
Maybe need a flag that we're messing with out-of-bounds indices.
For @Hallberg-NOAA

**Comment by kshedstrom** [comment]
> allocate(OBC%segment(0:OBC%number_of_segments))
Not necessarily so easy to "just add segments". Keep the old OBC structure, just copying out the old segments, then copy them back in? Build a new OBC structure and populate it? Does Fortran do deep copy by default? Scan through the segments once to see how many new ones will be needed or build a linked list as we go?

**Comment by kshedstrom** [comment]
Doing it differently. See the OBC wiki for reentrant handling.
