### ISSUE TITLE
Default OBC data values

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#67]
As I found in #66, external values are not being zeroed out by default. I have to explicitly specify values or else the model goes unstable. I think we should change this behavior to either (a) set them to zero or (b) complain and die. Anyone have a strong preference? @adcroft ?

I added a segment%values_needed flag for doing something about this, but it gets set to true [here,](https://github.com/ESMG/MOM6/blob/dev/esmg/src/core/MOM_open_boundary.F90#L633) then false [here](https://github.com/ESMG/MOM6/blob/dev/esmg/src/core/MOM_open_boundary.F90#L642). It is not subsequently checked. @MJHarrison-GFDL what does siz(4) have to do with anything?

Also, in looking at this part of the code, it would be nice if we could get rid of the "brushcutter" mode. Someday.

**Comment by MJHarrison-GFDL** [comment]
I don't like the idea of a zero default. We should fail if nothing is explicitly set.  

siz(4) is the extent of the external data in time.

**Comment by kshedstrom** [comment]
OK, will take a stab at it. Thanks for the siz(4) tip - not what I expected.

**Comment by kshedstrom** [comment]
A related issue - the model is never parsing these strings:
```
OBC_SEGMENT_001_DATA = "U=value:0.0,V=value:0.0,SSH=value:0.0" !
```
For circle_obcs, I changed it to:
```
OBC_SEGMENT_001_DATA = "U=value:0.0,V=value:0.0,SSH=value:1.0" !
```
and the answer didn't change.

**Comment by kshedstrom** [comment]
Or maybe the barotropic mode isn't using the values.

**Comment by kshedstrom** [comment]
Things are in place to be checking for values (and using them), but there are still issues:

If you have the first few strings like:
```
OBC_SEGMENT_001_DATA = "U=value:0.0,V=value:0.0,SSH=value:1.0"
```
but then are missing the rest, the code at [get_param](https://github.com/ESMG/MOM6/blob/dev/esmg/src/core/MOM_open_boundary.F90#614) returns with the same value in segstr as before (from the first segment), so the code thinks all is well. Setting segstr to "" or deleting all of the SEGMENT_xx_DATA strings causes the code to fail:

> At line 1462 of file //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/framework/MOM_file_parser.F90
Fortran runtime error: End of record
Advice, @adcroft, @MJHarrison-GFDL ?

**Comment by kshedstrom** [comment]
Fixed the parsing.
