### ISSUE TITLE
Tracer OBC reservoir questions

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#75]
I don't see how the tracer reservoir restarts can be right. The initialization calls fill_temp_salt_segments which fills them based on the model's T and S values just in from the boundary. Then there's update_OBC_segment_data which fills T and S reservoirs the first time it is called, copying over the input T and S values.

As for the reservoir updates, I see it happening twice in MOM_tracer_advect.F90, first at https://github.com/ESMG/MOM6/blob/dev/esmg/src/tracer/MOM_tracer_advect.F90#L457 and again at https://github.com/ESMG/MOM6/blob/dev/esmg/src/tracer/MOM_tracer_advect.F90#L650 . Is that the way it should be? @MJHarrison-GFDL @adcroft

**Comment by adcroft** [comment]
The update with implicit time-stepping should happen after all the explicit
terms are known.

>

**Comment by kshedstrom** [comment]
@MJHarrison-GFDL are you working on the update_segment_tracer_reservoirs routine or am I? The Lscale change needs to go there.

**Comment by MJHarrison-GFDL** [comment]
I was planning on doing it, but still working on the vorticity restart problem. You are welcome to do it if you have the time.

**Comment by kshedstrom** [comment]
Next question: For the tracer reservoirs, "inflow" is flow into the reservoir from the model while "outflow" is flow from external data into the reservoir. I'd like to switch them. Any objections?
@adcroft @MJHarrison-GFDL 

My PR fixes two issues, but not the restart.

**Comment by MJHarrison-GFDL** [comment]
OK be me.

**Comment by kshedstrom** [comment]
Closing this, will open a new issue.
